# Generated by Django 2.2.3 on 2019-07-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studij', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('email_ver', models.BooleanField(default=False)),
                ('studij_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studij.Studij')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Kolegij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolegij_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studij.Kolegij')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Student')),
            ],
        ),
    ]
