# Generated by Django 2.2.1 on 2019-08-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studij', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moji_Kolegiji',
            new_name='Student_Kolegij',
        ),
    ]
