# Generated by Django 2.2.1 on 2019-09-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studij_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studij.Studij'),
        ),
    ]
