# Generated by Django 2.2.4 on 2019-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stars',
            field=models.SmallIntegerField(default=1),
        ),
    ]
