# Generated by Django 2.2.1 on 2019-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='/profile_image/default.png', upload_to='profile_image'),
        ),
    ]
