# Generated by Django 2.2.1 on 2019-09-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studij', '0004_auto_20190911_0819'),
        ('account', '0002_auto_20190911_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studij_id',
        ),
        migrations.AddField(
            model_name='student',
            name='studij',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studij.Studij'),
            preserve_default=False,
        ),
    ]
