# Generated by Django 2.2.1 on 2019-09-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studij', '0004_auto_20190911_0819'),
        ('account', '0003_auto_20190911_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moj_kolegij',
            name='studij_id',
        ),
        migrations.AddField(
            model_name='moj_kolegij',
            name='studij',
            field=models.ForeignKey(default='pss', on_delete=django.db.models.deletion.CASCADE, to='studij.Studij'),
        ),
    ]
