# Generated by Django 2.2.1 on 2019-09-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190911_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moj_kolegij',
            name='smjer',
        ),
    ]
