# Generated by Django 2.2.1 on 2019-09-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studij_id', models.CharField(max_length=10)),
                ('studij_ime', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Smjer',
            fields=[
                ('smjer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('smjer_ime', models.CharField(max_length=60)),
                ('studij_id', models.ForeignKey(default='pss', on_delete=django.db.models.deletion.CASCADE, to='studij.Studij')),
            ],
        ),
        migrations.CreateModel(
            name='Kolegij',
            fields=[
                ('dummy_id', models.AutoField(primary_key=True, serialize=False)),
                ('kolegij_id', models.CharField(max_length=10)),
                ('kolegij_ime', models.CharField(max_length=60)),
                ('semestar', models.SmallIntegerField()),
                ('smjer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studij.Smjer')),
                ('studij_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studij.Studij')),
            ],
        ),
    ]
