# Generated by Django 2.2.1 on 2019-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studij', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studij',
            name='id',
        ),
        migrations.AlterField(
            model_name='studij',
            name='studij_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
