# Generated by Django 2.2.1 on 2019-09-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studij', '0002_auto_20190911_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smjer',
            name='studij_id',
        ),
        migrations.AddField(
            model_name='smjer',
            name='studij',
            field=models.ForeignKey(default='pss', on_delete=django.db.models.deletion.CASCADE, to='studij.Studij'),
        ),
    ]
