# Generated by Django 2.2.1 on 2019-09-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studij', '0003_auto_20190911_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kolegij',
            name='smjer_id',
        ),
        migrations.RemoveField(
            model_name='kolegij',
            name='studij_id',
        ),
        migrations.AddField(
            model_name='kolegij',
            name='smjer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studij.Smjer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kolegij',
            name='studij',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studij.Studij'),
            preserve_default=False,
        ),
    ]
