# Generated by Django 2.2.4 on 2019-08-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studij', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('tema_id', models.AutoField(primary_key=True, serialize=False)),
                ('tema_ime', models.CharField(max_length=50)),
                ('kolegij_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studij.Kolegij')),
            ],
        ),
    ]
