# Generated by Django 2.2.1 on 2019-09-11 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objava',
            fields=[
                ('objava_id', models.AutoField(primary_key=True, serialize=False)),
                ('kolegij_id', models.CharField(default='NN', max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tekst', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tema.Tema')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objava_Prijava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objava_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objava.Objava')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objava_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objava_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objava.Objava')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objava_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, max_length=500, null=True, upload_to='objava_att/')),
                ('objava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objava.Objava')),
                ('tema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tema.Tema')),
            ],
        ),
    ]
