# Generated by Django 2.2.4 on 2019-08-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0001_initial'),
        ('objava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objava_files',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tema.Tema'),
        ),
    ]
