# Generated by Django 2.2.4 on 2019-08-08 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 17, 46, 21, 303734, tzinfo=utc)),
        ),
    ]
