# Generated by Django 2.2.1 on 2019-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='kolegij_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='objava',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
