# Generated by Django 2.2.4 on 2019-08-07 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editobjave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 18, 43, 6, 230380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 18, 43, 6, 229979, tzinfo=utc)),
        ),
    ]
