# Generated by Django 2.2.4 on 2019-08-10 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objava', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objava',
            name='likes',
        ),
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 8, 52, 10, 555394, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Objava_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objava_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objava.Objava')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
