# Generated by Django 2.2.1 on 2019-08-05 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0002_auto_20190804_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editobjave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 18, 12, 7, 497665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 18, 12, 7, 496665, tzinfo=utc)),
        ),
    ]
