# Generated by Django 2.2.4 on 2019-08-10 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0002_auto_20190810_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 9, 4, 50, 238594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='objava',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tema.Tema'),
        ),
    ]
