# Generated by Django 2.2.3 on 2019-08-07 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0002_auto_20190807_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objava',
            name='allow_edit',
        ),
        migrations.AddField(
            model_name='objava',
            name='tema',
            field=models.CharField(default='NN', max_length=50),
        ),
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 20, 52, 25, 584407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='objava',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EditObjave',
        ),
    ]
