# Generated by Django 2.2.4 on 2019-08-11 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0002_auto_20190811_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 17, 43, 47, 58708, tzinfo=utc)),
        ),
    ]
