# Generated by Django 2.2.1 on 2019-08-09 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0002_auto_20190809_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 11, 42, 41, 293140, tzinfo=utc)),
        ),
    ]
