# Generated by Django 2.2.1 on 2019-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0002_auto_20190812_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='kolegij_id',
            field=models.CharField(max_length=500),
        ),
    ]
