# Generated by Django 2.2.1 on 2019-08-09 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0003_auto_20190809_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 11, 44, 15, 463622, tzinfo=utc)),
        ),
    ]
