# Generated by Django 2.2.4 on 2019-08-08 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0003_auto_20190808_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 17, 47, 6, 385302, tzinfo=utc)),
        ),
    ]
