# Generated by Django 2.2.1 on 2019-08-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0003_auto_20190812_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='objava_att/'),
        ),
        migrations.AlterField(
            model_name='objava',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
