# Generated by Django 2.2.1 on 2019-08-08 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0003_auto_20190807_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 16, 10, 9, 981657, tzinfo=utc)),
        ),
    ]
