# Generated by Django 2.2.1 on 2019-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objava', '0004_auto_20190812_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='objava_att/'),
        ),
    ]
